name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt install -y golang-1.21 ruby
        sudo gem install fpm

    - name: Build binary
      run: |
        export PATH=${PATH}:/usr/lib/go-1.21/bin
        make kuvasz-agent

    - name: Build package
      run: make package
